### ISSUE TITLE
License info?

### ISSUE THREAD

**Issue by trelau** [mlivesu/slice2mesh#1]
Great work! Have you chosen an open source license for this work (e.g., BSD, MIT, etc.)? If you have, I'd recommend adding the license file to the repo.

**Comment by mlivesu** [comment]
Thanks Trevor! We followed your suggestion and added a license for this project. We opted for the MPL 2.0 license. Please note that MPL applies only to our original code, while external dependencies (such as Boost, Tetgen and Triangle) come with their own license.
